<?php

namespace AppBundle\Repository;

/**
 * boat_workerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boat_workerRepository extends \Doctrine\ORM\EntityRepository
{
}
