<?php

namespace AppBundle\Repository;

/**
 * boatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boatRepository extends \Doctrine\ORM\EntityRepository
{
}
