<?php

namespace AppBundle\Repository;

/**
 * workerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workerRepository extends \Doctrine\ORM\EntityRepository
{
}
